### ISSUE TITLE
Compulsory to convert raw data to mat format?

### ISSUE THREAD

**Issue by akmal871026** [villekf/OMEGA#10]
Hi villekf/OMEGA,

If I have PET raw data, is it compulsory to convert it to mat format to run using main_Pet.m?

**Comment by villekf** [comment]
Yes, raw data has to be in mat-format and also be formatted exactly as it is created in OMEGA.

List-mode support for additional devices will probably be expanded in the future, but raw data support will not be expanded in this regard.
