### ISSUE TITLE
No ASCII (.dat) coincidence files were found

### ISSUE THREAD

**Issue by akmal871026** [villekf/OMEGA#11]
Hi villekf/OMEGA,

why i run `gate_main_simple.m` the error pop up below?

```
Error using load_data (line 575)
No ASCII (.dat) coincidence files were found. Check your filepath (options.fpath) or current
folder.

Error in gate_main_simple (line 420)
    options.coincidences = load_data(options);
```

is it have to locate the raw data that you give here https://doi.org/10.5281/zenodo.3522199 in somewhere folder?

**Comment by villekf** [comment]
You are missing GATE simulated ASCII data. Check the [tutorial](https://github.com/villekf/OMEGA/wiki/Tutorial) for details. You can simulate your own data with the provided macros.

**Comment by akmal871026** [comment]
Then how to get the data?
