### ISSUE TITLE
BSREM ALGORITHM

### ISSUE THREAD

**Issue by akmal871026** [villekf/OMEGA#12]
Hi Sir, want to ask you.

Did your algorithm Block Sequential Regularized Expectation Maximization (BSREM)  [14]  is same with 
Bayesian penalized likelihood reconstruction algorithm (BSREM) ??

**Comment by villekf** [comment]
Since you did not provide a reference, I do not know, but probably not. Check your reference with the [14] to see if they are alike.

Closing this since it's not an issue with the software itself.

**Comment by akmal871026** [comment]
Hi sir,

Here i attached the reference.
