### ISSUE TITLE
Unrecognized function or variable 'vol3d'.

### ISSUE THREAD

**Issue by akmal871026** [villekf/OMEGA#16]
Dear villekf,

i run the code for `visualize_pet.m`

but the error pop up below. How to solve it?

```
Unrecognized function or variable 'vol3d'.

Error in visualize_pet (line 371)
figure;vol3d('CData', permute(img(:,:,:,end), [3 2 1 4]), 'Alpha', alpha);
 
```

**Comment by villekf** [comment]
`visualize_pet.m` already has information on how to solve this:

`% NOTE: Use of this section requires vol3D v2`
`% Download: `
`% https://se.mathworks.com/matlabcentral/fileexchange/22940-vol3d-v2`
