### ISSUE TITLE
Inveon_PET_main.m issue

### ISSUE THREAD

**Issue by June-phy** [villekf/OMEGA#18]
Hi sir,
I am a rookie in this field. When I run the Inveon data from Zenodo

`>>Inveon_PET_main`

the error pop up as below

 ```
Error using inveon_list2matlab
 16 input arguments required.

Error in load_data (line 175)
     [LL1, LL2, tpoints, DD1, DD2, raw_SinM, SinD] =
     inveon_list2matlab(nimi,(vali),(alku),(loppu),pituus, uint32(detectors),
     options.randoms_correction, sinoSize, ...

 Error in Inveon_PET_main (line 1680)
     options.coincidences = load_data(options);

```
Can someone tell the problem is?

**Comment by villekf** [comment]
You seem to be using an older version of `load_data.m` and newer version of the MEX-file `inveon_list2matlab`. Did you install the latest version? Is MATLAB perhaps finding an older version of the software?

**Comment by June-phy** [comment]
I install the latest version. 
It works! Thank you sir.
But a new error pop up as below
```
Error using  : 
Colon operands must be real scalars.

Error in padding (line 14)
for i=1:paddingSize

Error in computeConvolution (line 60)
vec = padding(vec, [g_dim_x g_dim_y g_dim_z]);

Error in reconstructions_main (line 1516)
                                OSEM_apu = computeConvolution(im_vectors.OSEM_apu,
                                options, Nx, Ny, Nz, gaussK);

Error in attenuation_correction_factors (line 80)
    pz = reconstructions_main(options);

Error in Inveon_PET_main (line 1710)
    options.attenuation_datafile = attenuation_correction_factors(options);
```
Can you deal with this problem?

**Comment by June-phy** [comment]
I install the latest version.
It works! Thank you sir.
But a new error pop up as below

Error using  : 
Colon operands must be real scalars.

Error in padding (line 14)
for i=1:paddingSize

Error in computeConvolution (line 60)
vec = padding(vec, [g_dim_x g_dim_y g_dim_z]);

Error in reconstructions_main (line 1516)
                                OSEM_apu = computeConvolution(im_vectors.OSEM_apu,
                                options, Nx, Ny, Nz, gaussK);

Error in attenuation_correction_factors (line 80)
    pz = reconstructions_main(options);

Error in Inveon_PET_main (line 1710)
    options.attenuation_datafile = attenuation_correction_factors(options);


Can you deal with this problem?













At 2021-02-14 00:02:39, "villekf" <notifications@github.com> wrote:

You seem to be using an older version of load_data.m and newer version of the MEX-file inveon_list2matlab. Did you install the latest version? Is MATLAB perhaps finding an older version of the software?

**Comment by villekf** [comment]
You seem to have another function called `padding.m` that is not related to OMEGA. MATLAB attempts to use this one, but it obviously is not compatible with OMEGA code. I'd recommend either renaming that non-OMEGA `padding.m` or remove it from the path. You should be able to see its location with `edit padding.m`.

In the next version, I might change the name of the `padding.m` to avoid conflicts in the future, but for now the above should be the way to go.

**Comment by June-phy** [comment]
I remove my original `padding.m`. The problem has been solved. Thank you sir!
A new error pop up as below just at the beginning of Normalization correction:
```
Error using fread
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in set_up_corrections (line 712)
            options.normalization = fread(fid, inf, 'single=>single',0,'l');

Error in reconstructions_main (line 808)
    [normalization_correction, randoms_correction, options] =
    set_up_corrections(options, blocks, RandProp, ScatterProp);

Error in Inveon_PET_main (line 1733)
    pz = reconstructions_main(options);
```
Do you know why it is?

**Comment by villekf** [comment]
Apparently the previous version of `set_up_corrections` only checks the current working directory. I've now fixed it to use the full path when selecting the file. You can either download the fixed file [here](https://raw.githubusercontent.com/villekf/OMEGA/master/source/set_up_corrections.m) and replace the old file in the source-folder with the new one, or simply move the normalization file to the current folder selected in MATLAB.

**Comment by June-phy** [comment]
All the problem have been solved.
Thank you so much！！！！
