### ISSUE TITLE
ROOT issue

### ISSUE THREAD

**Issue by June-phy** [villekf/OMEGA#23]
Hi sir,
I was  using OMEGA on MacOS.
When I run `install_mex`
some warning pomp up as below
```
warning: Unable to build ROOT support! If you do not need ROOT support ignore this warning.
Otherwise make sure that ROOT was compiled with the same compiler you are using to
compile this mex-file and provide the path to ROOT install folder with install_mex(0, [],
[], [], '/path/to/ROOT'). Compiler error is shown with install_mex(1) 
> In install_mex (line 456) 
```
```
warning: CUDA support not enabled 
> In install_mex (line 587) 
```
How to solve this problem?

**Comment by villekf** [comment]
You can see the error message by running `install_mex(1)`. The most likely reason is that ROOT could not be found. If that is the case, you could try `install_mex(0, [],[], [], '/path/to/ROOT')` and input the folder where ROOT is installed (include and lib folders should be in the path you input). If you don't need ROOT support, you can ignore the warning.

CUDA, on the other hand, is not supported on MacOS.

**Comment by June-phy** [comment]
I found several folders named 'root' or 'ROOT'. Which is the right path?



At 2021-03-30 14:51:49, "villekf" ***@***.***> wrote:

You can see the error message by running install_mex(1). The most likely reason is that ROOT could not be found. If that is the case, you could try install_mex(0, [],[], [], '/path/to/ROOT') and input the folder where ROOT is installed (include and lib folders should be in the path you input). If you don't need ROOT support, you can ignore the warning.

CUDA, on the other hand, is not supported on MacOS.

**Comment by villekf** [comment]
How did you install ROOT? There are several ways to do that for MacOS, as shown [here](https://root.cern/install/).

**Comment by June-phy** [comment]
Dear sir，
I installed ROOT twice, from Macports and Homebrew respectively.
Anyway, I restall it and add the path as below
 `install_mex(0, [],[], [], '/Applications/root_v6.22.08/to/ROOT')`
but it pop up the same warning
```
warning: Unable to build ROOT support! If you do not need ROOT support ignore this warning.
Otherwise make sure that ROOT was compiled with the same compiler you are using to compile
this mex-file and provide the path to ROOT install folder with install_mex(0, [], [], [],
'/path/to/ROOT'). Compiler error is shown with install_mex(1) 
> In install_mex (line 456) 
```
I hope to use ROOT data because it may save a lot of space.

**Comment by villekf** [comment]
Have you done the step `Add the ROOT libraries and executables to your environment by sourcing the appropriate thisroot.* script. These setup scripts can be found in the ROOT binary release, in the bin directory.`? More specifically, does `root-config` command produce any output when you use it on terminal? On MacOS (and Linux), OMEGA uses the `root-config` command to build the ROOT files (the ROOT path is actually only used on Windows) so this needs to work. 

I'll clarify the warning message in the next version as well.

**Comment by June-phy** [comment]
I am so sorry. But I checked `root-config` command, it does have the output.
I also checked the folder and found the root-config to make sure the PATH is right.
Why the warning says `command not found`?
```
/var/folders/tq/03lp__cs5zx2zlmc1bfmn3fc0000gn/T/mex_6717118933742_623: line 2: root-config: command not found
warning: Unable to build ROOT support! If you do not need ROOT support ignore this warning. Otherwise make
sure that ROOT was compiled with the same compiler you are using to compile this mex-file and provide the
path to ROOT install folder with install_mex(0, [], [], [], '/path/to/ROOT'). Compiler error is shown with
install_mex(1) 
```

**Comment by villekf** [comment]
If `root-config` is in your PATH, then it should find it. I have not been able to test ROOT-support on MacOS though, so there might be some Mac-specific requirements. 

One way to get the compilation working would probably be for you to modify `install_mex` and change `root-config` to `/Applications/root_v6.22.08/to/ROOT/bin/root-config`. 

I'll change the file in the next version such that the the `/path/to/ROOT` would then be used with `root-config`.

**Comment by June-phy** [comment]
I replace all the `root-config` with the new address `/usr/local/Cellar/root/6.22.06_2/bin/root-config` in `install_mex`.
It works! I am so happy.
All I could say is--thanks!!!!!!
