### ISSUE TITLE
gate_main.m issue

### ISSUE THREAD

**Issue by June-phy** [villekf/OMEGA#24]
Hi,
 When I run `gate_main.m` on Mac, the error pop up as below:
```
Error using save
Cannot create 'Cylindrical_PET_example_lor_pixel_count_128x128x63_sino_200x168x703.mat'
because '/Users/shanqianxue/Library/Application Support/MathWorks/MATLAB
Add-Ons/Toolboxes/OMEGA - Open-mat-files/ MATLAB emission tomography
software/mat-files' does not exist.

Error in lor_pixel_count_prepass (line 455)
                    save(file_string,'lor','-v7.3')

Error in precompute_data (line 46)
    lor_pixel_count_prepass(options);

Error in gate_main (line 1639)
   precompute_data(options);
```
 Because there is a space before  the file name `MATLAB emission tomography software`. 
But I didn't find the way to correct it in `inlor_pixel_count_prepass.m`. 
How can I change the save path?

**Comment by villekf** [comment]
This is indeed a bug when using the toolbox-version. For a quick workaround, simply replace line 100 in `lor_pixel_count_prepass.m` with `folder = [folder(1:end-6), 'mat-files/'];`

This bug is not limited to only this file, but others as well (same fix works there). These will be fixed in the next release.

**Comment by villekf** [comment]
The current master branch now contains the same fix as outlined above.

**Comment by June-phy** [comment]
Thank you sir!
And I found another problem in `gate_main.m`.
I want to use `ndist_max.m` to get number of radial positions (views) in sinogram, so I replace line 300 with `options.Ndist = ndist_max(options)`.
The error pop up as below:
```
Reference to non-existent field 'implementation'.

Error in detector_coordinates (line 219)
if (options.implementation == 2 || options.implementation == 3 ||
options.implementation == 5) && options.listmode > 0

Error in ndist_max (line 56)
    [x, y] = detector_coordinates(options);

Error in gate_main (line 300)
options.Ndist = ndist_max(options);
```
The problem can be solved by moving line 788 `options.implementation = 4` before the `ndist_max.m`
