### ISSUE TITLE
output reconstruction direction

### ISSUE THREAD

**Issue by imanazinkhah** [villekf/OMEGA#30]
Hello. Thank you so much for this great app. I have reconstructed the output of a GATE CT scan simulation with this program. But I could not find the output direction of the final reconstruction. Where to save the reconstructed file? thanks a lot

**Comment by villekf** [comment]
Hi,

If you are referring to the final reconstructed images, they should be stored either in the `pz` variable or in `f_osem`. Depending on how you performed the reconstruction.

**Comment by imanazinkhah** [comment]
Thank you very much🙏🙏🙏
