### ISSUE TITLE
Self-designed CT reconstruction using OMEGA

### ISSUE THREAD

**Issue by zhijunzhao714** [villekf/OMEGA#42]
Dear villekf,
   I am using OMEGA for my self-designed CT image reconstruction, but the output image is inconsistent with the phantoml I designed, is there any way to solve it? 
  The following are the parameters set during reconstruction, the projection image obtained from CT, and the reconstructed image, and the phantom image.
 
options.binning = 1;
options.xSize = 1536/options.binning;
options.ySize = 1536/options.binning;
options.nProjections = 360;
options.angles = -linspace(0, 359, options.nProjections);
options.dPitch = 0.139*options.binning;
options.sourceToDetector = 389.4;
options.sourceToCRot = 254;
options.name = 'OURSELF_CT_data';
options.only_reconstructions = false;
options.verbose = true;
options.FOVa_x = 102.4;
options.FOVa_y = options.FOVa_x;
options.axial_fov = 102.4; 

Projection image:
![image](https://github.com/villekf/OMEGA/assets/110451114/d95b6f7c-471f-4194-b779-73ff081c9ac8)
Reconstructed image:
![image](https://github.com/villekf/OMEGA/assets/110451114/d4f79099-3529-4022-9a7a-8c7f8e92089e)
Phantom image:
![image](https://github.com/villekf/OMEGA/assets/110451114/900e9cb3-e155-4756-b71a-08eed5b911de)

best wishes

**Comment by zhijunzhao714** [comment]
Dear villekf,
   I used data acquired from real CT equipment, I put my data on the Zenodo , https://zenodo.org/deposit/8079243 , and I also want to ask the coordinate system in OMEGA is Dicom coordinate system or IEC coordinate system?

![image](https://github.com/villekf/OMEGA/assets/110451114/4791b3d7-c4f9-496a-8ea2-b7dc0ae3d2b7)

best wishes

**Comment by zhijunzhao714** [comment]
Dear villekf,
I used data acquired from real CT equipment, I upload my data on the Zenodo , https://zenodo.org/record/8079243 , and I also want to ask the coordinate system in OMEGA is Dicom coordinate system or IEC coordinate system?

In this picture, "坐标系" is "coordinate system".
![image](https://github.com/villekf/OMEGA/assets/110451114/5273ec2c-2534-4d91-814c-bf5b6838440c)

best wishes

**Comment by villekf** [comment]
It is Dicom coordinate system, though the y and x might be flipped. The CT coordinate system is based on Siemens Inveon coordinate system.

**Comment by zhijunzhao714** [comment]
Dear villekf,
Thank you very much for your reply. The CT system I built uses IEC coordinate system. I have tried to change the Angle according to the method you said (tested several different angle settings), and I have also tried to modify the coordinate system (options.x, options.y, options.z). Many different modification schemes were tried, but the results were all incorrect.
best wishes

**Comment by villekf** [comment]
Note that your projections should rotate in the up-down axis. From the looks of your image previously, it seems to rotate in the left-right axis. You could try rotating your projections 90 degrees.

**Comment by zhijunzhao714** [comment]
Dear professor,
The projection image plot in matlab using imagesc is :
![image](https://github.com/villekf/OMEGA/assets/110451114/c067ffee-62bd-4410-a910-068d448ff742)
in this view, the projection is rotate in the up-down axis , and I also follow your suggestions (change, rotate my projections ), but the results are still incorrect.
I tried so many times, I couldn't get the right image, I really can't think of a way to solve this problem, so I would like to ask for your help.
best wishes

**Comment by villekf** [comment]
I can't recall anymore how the rotation should be done in the older (meaning current) version. It has to be in the top-down axis though which it clearly is now. Have you tried flipping the projections, i.e. that the object is on the left side rather than on the right side? Another thing you could do, is to check the [Siemens Inveon CT data](https://zenodo.org/record/4646835) and get things as close to it as possible. This means that the rotation of the projections is similar as well as sign of the difference between angles (meaning that the angles either increase or decrease).

If it helps, the current version works when the projections are rotated from bottom to top when an object is nearest the panel (if this makes any sense) and with decreasing angles. The opposite should also work though.

**Comment by zhijunzhao714** [comment]
Dear villekf,
  Anyway, still want to thank you, thank you very much for your reply, and I'm look forward to the next version of OMEGA. Also, can I ask when the next version of OMEGA will be released?
best wishes

**Comment by villekf** [comment]
That's a good question. Hopefully sometime in the autumn, but right now I can't give anything more specific.

**Comment by zhijunzhao714** [comment]
Thank you very much, I will be looking forward to it.
