### ISSUE TITLE
problem when trying to reconstruct mCT and Vision data

### ISSUE THREAD

**Issue by xtsinghua** [villekf/OMEGA#45]
Hello, there:
I am trying to using devel version to reconstruct mCT(32-bit list mode) and Vision(64-bit list mode) raw data.
Both have problems.
For mCT, the code stopped when trying to load the data. Below is the screent print when running the code:
"">> Biograph_mCT_main
Using 32-bit list-mode data with TOF (13 bins).
Using implementation 4.
OSEM reconstruction method selected.
No precomputed data will be used.
Improved Siddon's algorithm used with 1 transaxial ray and 1 axial ray.
Randoms correction ON.
Sinogram gap filling ON.
Corrections applied during reconstruction (ordinary Poisson).
Using STATIC sinogram data (prompts).
Every 8th column measurement is taken per subset.
Using an image (matrix) size of 128x128x109 with 3 iterations and 8 subsets.
Beginning data load""

And the error is as shown in figure 1.

For Vision, the code can load the data successfully but the matlab quit after "Start Reconstruction".

I attached the list mode data for both mCT and Vision and could you please help me to figure it out what is the problem?

https://drive.google.com/file/d/1z4BM0mJ0gWlOGrUuEdni5NxnQCHxsNTf/view?usp=drive_link

Thank you so much.
Ethan
![Uploading figure1.png…]()

**Comment by villekf** [comment]
This issue was solved in the discussions.
