### ISSUE TITLE
Issue when running Inveon_PET_main.m

### ISSUE THREAD

**Issue by inemar2** [villekf/OMEGA#47]
Dear sir,
Hello. In Inveon_PET_main.m ,when I run the code in MATLAB, an error occurs: 
>> Inveon_PET_main
Unrecognized function or variable 'OMEGA_error_check'.

Error in Inveon_PET_main (line 1739)
options = OMEGA_error_check(options);

How do I solve this problem？
Thanks.

**Comment by villekf** [comment]
Did you add the source-folder into Matlab/Octave path?

**Comment by inemar2** [comment]
Yes, I think so. I added to the folder of MATLAB. I share a screenshot.
![screenshot](https://github.com/villekf/OMEGA/assets/157502594/30c4dcd3-dc5d-4ec8-86dc-a9efc6cca273)

**Comment by villekf** [comment]
The source-folder is grayed out, this means that it is not on path and thus Matlab can't find any of the functions. The folder needs to be "black" like OMEGA-master to be included. Simply right-click the source-folder and select the "Add to Path" (either of the options are valid for the current version). Note that you need to do this every time to open Matlab. If you want a permanent solution, add the folder to "Home --> Set Path".

**Comment by inemar2** [comment]
Thank you! Do you have a virtual machine or a docker with this software where I can perform tests ?

**Comment by villekf** [comment]
Unfortunately no. My resources are quite thin as it is. A docker implementation would definitely be useful, but not sure how easy it would be to implement it for this case. Maybe in the future, but I don't recommend holding your breath for it.

**Comment by inemar2** [comment]
Ok, thank you for the rapid response!

**Comment by inemar2** [comment]
It works in latest versions of MATLAB?

**Comment by villekf** [comment]
Yes, it should. I don't think any of the functions I've used have been removed. I did a few tests on 2023b recently with the master-branch version too.

**Comment by villekf** [comment]
In order to use implementation 2, you need to install ArrayFire. See the wiki: [https://github.com/villekf/OMEGA/wiki/Installation-help#arrayfire](https://github.com/villekf/OMEGA/wiki/Installation-help#arrayfire)

`install_mex` shows errors only when used as `install_mex(1)`. Otherwise only warnings are displayed.

**Comment by villekf** [comment]
Closing as resolved.
