### ISSUE TITLE
main_PET.m issue

### ISSUE THREAD

**Issue by akmal871026** [villekf/OMEGA#7]
Dear sir, when I want to run my own raw data PET, I use this code 

`>> main_PET.m`

but error like below pop up

```
Error using OMEGA_error_check (line 304)
Implementation 4 supports only one OS and one MLEM algorithm at a time.

Error in main_PET (line 1390)
options = OMEGA_error_check(options);
```

can someone tell the problem is?

**Comment by villekf** [comment]
Set `options.OSL_OSEM` on line 851 to false. It was erroneously set as true on default.

**Comment by akmal871026** [comment]
yes. it work. but havelittle bit error

```
Starting image reconstruction
Index exceeds matrix dimensions.

Error in reconstructions_main (line 3378)
                                uu = double(full(Sino(pituus(osa_iter)+1:pituus(osa_iter +
                                1))));

Error in main_PET (line 1480)
    pz = reconstructions_main(options);
```

**Comment by villekf** [comment]
What data are you using? Your own data or the one from Zenodo?

**Comment by akmal871026** [comment]
my own data. from pet ct scan. the raw data

**Comment by akmal871026** [comment]
can you give me your email so that I can share with you my own raw data. please help me.

**Comment by villekf** [comment]
Then the device/sinogram specific variables are most likely wrong. You should double-check them.

Furthermore, the input data needs to be in sinogram format, not in list-mode format.

**Comment by villekf** [comment]
If the input data is not Siemens Biograph list-mode data or Inveon data, I cannot help you. You need to contact the device manufacturer for assistance in reading the data.

**Comment by akmal871026** [comment]
OH I SEE.. BECAUSE MY DATA FROM GE BRAND.
