### ISSUE TITLE
How to see the image have done reconstruction

### ISSUE THREAD

**Issue by akmal871026** [villekf/OMEGA#9]
Hi villekf/OMEGA,

I have run main.PET.m using below data that you giving in  your website as below

`Cylindrical_PET_example_cylpet_example_sinograms_combined_static_200x168x703_span3.mat`

but the final command it just write `Reconstruction process took 327.4303 seconds`

NO IMAGE appear.

How to see the image have done reconstruction?

**Comment by villekf** [comment]
See [visualization](https://github.com/villekf/OMEGA/wiki/Visualization) in the wiki for more information.

In short, you have to either manually visualize the image (with e.g. imagesc) or use visualize_pet.m for visualization.

**Comment by akmal871026** [comment]
But where is the image reconstructed located?

**Comment by villekf** [comment]
If you used `gate_main_simple.m` then `f_osem`. Otherwise `pz`. I've updated the [tutorial](https://github.com/villekf/OMEGA/wiki/Tutorial) to be more clear on this.

**Comment by akmal871026** [comment]
So the data this one is for run main_PET.m or simple_main_gate.m?



For reconstruction purposes, ready-made example raw data and sinograms can
be found from: https://doi.org/10.5281/zenodo.3522199
